### ISSUE TITLE
incompatability with 1.6.0.7

### ISSUE THREAD

**Issue by Willster419** [Aimdrol/MLG-Illuminati-Companion#3]
Hi,
There is a compatibility issue with the companion with 1.6.0.7. Similar to 1.6.0.2 I think.

`2019-09-20 20:59:55.389: ERROR: Traceback (most recent call last):
2019-09-20 20:59:55.389: ERROR:   File "scripts/client/Avatar.py", line 2279, in updateArena
2019-09-20 20:59:55.389: ERROR:   File "scripts/client_common/ClientArena.py", line 288, in update
2019-09-20 20:59:55.389: ERROR:   File "mod_Companion.py", line 121, in new_onVehicleKilled`

**Comment by Aimdrol** [comment]
Yes, they reverted the change from 1.6.0.2

Fixed with a46fcb7c34a3b19e21331b40dfe675ec272d154d
